server:
  port: 8080

spring:
  # 데이터베이스 설정
  datasource:
    url: jdbc:postgresql://localhost:5432/security_login_db
    username: your_username
    password: your_password
    driver-class-name: org.postgresql.Driver

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: update  # 테이블 자동 생성/수정
    show-sql: true      # SQL 쿼리 콘솔 출력
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  # Thymeleaf 설정
  thymeleaf:
    cache: false        # 개발 중 캐시 비활성화
    prefix: classpath:/templates/
    suffix: .html

  # OAuth2 클라이언트 설정
  security:
    oauth2:
      client:
        registration:
          # Google OAuth2
          google:
            client-id: ${GOOGLE_CLIENT_ID:your-google-client-id}
            client-secret: ${GOOGLE_CLIENT_SECRET:your-google-client-secret}
            scope: profile, email
            redirect-uri: http://localhost:8080/login/oauth2/code/google

          # Kakao OAuth2
          kakao:
            client-id: ${KAKAO_CLIENT_ID:your-kakao-client-id}
            client-secret: ${KAKAO_CLIENT_SECRET:your-kakao-client-secret}
            scope: profile_nickname, account_email
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao

          # Naver OAuth2
          naver:
            client-id: ${NAVER_CLIENT_ID:your-naver-client-id}
            client-secret: ${NAVER_CLIENT_SECRET:your-naver-client-secret}
            scope: name, email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/naver

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

# JWT 설정
jwt:
  secret: ${JWT_SECRET:mySecretKey1234567890abcdefghijklmnopqrstuvwxyz}
  access-token-expiration: 3600000    # 1시간 (밀리초)
  refresh-token-expiration: 1209600000 # 14일 (밀리초)

# 로깅 설정
logging:
  level:
    com.example.securitylogin: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG